# k8s/product-service/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: cloudops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/product-service-role
