# k8s/user-service/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: cloudops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/user-service-role
